# To use Software Module Farm:
export MODULEPATH=$MODULEPATH:/global/software/sl-7.x86_64/modfiles/langs
export MODULEPATH=$MODULEPATH:/global/software/sl-7.x86_64/modfiles/tools
export MODULEPATH=$MODULEPATH:/global/software/sl-7.x86_64/modfiles/apps

# To use system locally installed cuda:
export PATH=/usr/local/cuda-11.2/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64:$LD_LIBRARY_PATH

# activate conda
eval "$(/clusterfs/ml4hep_nvme2/bpnachman/anaconda3/bin/conda shell.bash hook)"
